export const KailuvaStructure = {
  id: "52664451-feec-46c7-aa60-765bba87944d",
  title: "Kailuva Sikuvael",
  slug: "kailuva-sikuvael-person",
  state: "public",
  isWip: true,
  isDraft: false,
  entityClass: "Person",
  icon: "fa-solid fa-user-crown",
  url: "https://www.worldanvil.com/w/istralar-hanhula/a/kailuva-sikuvael-person",
  subscribergroups: [],
  folderId: "-1",
  tags: "sc2023,beings-elvn,tribes-nsrei",
  updateDate: {
    date: "2024-02-08 03:30:18.000000",
    timezone_type: 3,
    timezone: "Europe/London",
  },
  position: null,
  excerpt:
    "A Nisrei ambassador, world-wanderer, and bearer of the absolute worst luck.",
  wordcount: 1827,
  creationDate: {
    date: "2023-07-17 05:02:16.000000",
    timezone_type: 3,
    timezone: "Europe/London",
  },
  publicationDate: {
    date: "2023-07-17 08:40:26.000000",
    timezone_type: 3,
    timezone: "Europe/London",
  },
  notificationDate: {
    date: "2023-07-17 08:40:47.000000",
    timezone_type: 3,
    timezone: "Europe/London",
  },
  likes: 21,
  views: 530,
  userMetadata: null,
  articleMetadata: null,
  cssClasses: null,
  displayCss: null,
  templateType: "person",
  customArticleTemplate: null,
  editor: "code",
  content:
    "[quote]With Kailuva by my side, I'm delighted to live in interesting times!|Tuiravi[/quote]\r\n\r\nKailuva Sikuvael is a @[snow elven](ethnicity:4196c7ca-6679-46b7-a36e-c6ed8be75b3d) diplomat and explorer of the @[Nisrei](organization:5177657a-0219-4b38-ae53-0f19254114e2), formally holding the role of the @[Mountain's Eyes](profession:551e2258-31eb-4c3a-9b92-a555bf8430e1). Though originally based in @[Mount Firanthul](location:ddb13ca3-8197-4a55-bcf7-0a2e12f08265), Kailuva moved to @[the Tower of Sathelis](settlement:4aec5ad0-3a70-4b5e-981c-7007477118e1) to live with his wife, @[Tuiravi Amliris](person:ffc6b847-a340-453e-8de9-f5c549e7f517), shortly after their wedding.\r\n\r\nThough not an adventurer by any standards, Kailuva has developed a reputation for ending up in the most bizarre of places. Unlike many snow elves, he has travelled across many continents whilst carrying out his duties as the Mountain's Eyes, and has found himself stuck in many new and often bizarre situations along the way. He is a @[ranger](profession:c6c82fb0-3889-4f9d-8245-34ca82346ab8) by class, and so possesses some @[divine](technology:97a9e2b1-1ae3-412b-b915-f24e093cc3bf) abiliites to help him escape these tight spots. His wife (who often intervenes to help) refers to his luck as brilliant, but [i]highly[/i] cursed.\r\n\r\nKailuva and Tuiravi have three children: the arcane scholar @[Vairani](person:f6aadd39-6ade-4d37-be4d-0592894ff92d), the hunter-in-training @[Huiriase](person:d16bd0be-27a7-4adf-a3c9-4cc77375a070), and their surprise bonus child @[Iulómë](person:c647e2b7-ad8e-4188-bb09-0541837e01a7).",
  author: {
    id: "da93c838-919d-4963-a48b-e4ebd0b14114",
    title: "Hanhula",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "User",
    icon: "fa-solid fa-user",
    url: "https://www.worldanvil.com/author/Hanhula",
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  category: {
    id: "9b9be41e-6026-4998-88b2-9a17aa3fa392",
    title: "Inhabitants of the North",
    slug: "inhabitants-of-the-north-category",
    state: "public",
    isWip: null,
    isDraft: null,
    entityClass: "Category",
    icon: "fa-solid fa-folder",
    url: "https://www.worldanvil.com/w/istralar-hanhula/c/inhabitants-of-the-north-category",
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: {
      date: "2025-06-24 08:59:19.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  world: {
    id: "06a063ad-0a66-43da-ab88-7ff2941b854a",
    title: "Istralar",
    slug: "istralar-hanhula",
    state: "public",
    isWip: null,
    isDraft: null,
    entityClass: "World",
    icon: "fa-solid fa-globe-stand",
    url: "https://www.worldanvil.com/w/istralar-hanhula",
    subscribergroups: [
      {
        id: "92d18d7f-35fb-4955-8c33-83b32c42b44f",
        title: "Albie",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "97e9f894-dd7a-43c7-a6bc-872bdaacc7f1",
        title: "Aquabrodie",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "367d1c19-750f-4a7e-8777-399cd12b6bc0",
        title: "Chaos",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "a6ed4924-8d47-4f65-ab4e-636136b37f48",
        title: "Gets to know cool shit",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "2c83d1b4-0166-4c78-857c-beefdb2c360b",
        title: "Jazai",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "c39cb071-95ec-4794-841e-4ddf95181bb6",
        title: "Mouseshy",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "e3658168-5c2a-472e-ae0c-b59e73082414",
        title: "Owl",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "2b368a2a-d45f-410f-8ee6-05282cdf6a57",
        title: "The Lost Ones & Associates",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "7e7686a5-3b47-421d-85d1-539e5902b021",
        title: "WIP Readers",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
    ],
    folderId: "-1",
    tags: "",
    updateDate: {
      date: "2025-08-21 02:01:39.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  portrait: {
    id: 4699256,
    title: "Kailuva-Token.png",
    slug: null,
    state: "public",
    isWip: null,
    isDraft: null,
    entityClass: "Image",
    icon: "fa-solid fa-image",
    url: "https://www.worldanvil.com/uploads/images/5013df156410877ba86f1162fb134a7d.png",
    subscribergroups: [],
    folderId: "-1",
    tags: "",
    updateDate: {
      date: "2023-07-17 05:21:12.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  cover: {
    id: 4699488,
    title: "kailuva.webp",
    slug: null,
    state: "public",
    isWip: null,
    isDraft: null,
    entityClass: "Image",
    icon: "fa-solid fa-image",
    url: "https://www.worldanvil.com/uploads/images/d5b09740114a1a2e508f61c322ead5c2.webp",
    subscribergroups: [],
    folderId: "-1",
    tags: "",
    updateDate: {
      date: "2023-07-17 16:05:03.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  coverSource: "Person",
  pronunciation: null,
  snippet: null,
  seeded: null,
  sidebarcontent: null,
  sidepanelcontenttop: null,
  sidepanelcontent: null,
  sidebarcontentbottom:
    "[container:art-pic]\r\n[img:4195989]\r\n[/container]\r\n\r\n[container:art-pic]\r\n[img:4699254]\r\n[/container]\r\n\r\n[container:art-pic]\r\n[img:4699257]\r\n[/container]\r\n\r\n[quote]Don't you think we've got enough wolves?|a doubtful Kailuva to an unrepentant Tuiravi[/quote]\r\n\r\n[container:infobox]\r\n[h2]The Wolves[/h2]\r\nKailuva and Tuiravi have five snow wolves, each larger than the next. The largest, Halceleth, is Tuiravi's personal mount. Whilst Kailuva himself has never particularly claimed one, his wife makes it very much known that Kailuva [i]actually[/i] belongs to Mialyana, her wolf's mate.\r\n[/container]\r\n\r\n[quote]Would you really deprive our fluffy loves their family, darling?|Tuiravi to Kailuva[/quote]\r\n\r\n[container:art-pic]\r\n[img:4699451]\r\n[/container]\r\n\r\n[quote]Oh, yeah, the oldest is pregnant again. I think my mother said she's naming the next one after my father's hair.|Vairani on the wolves, in earshot of her father[/quote]",
  footnotes: null,
  fullfooter: null,
  authornotes: null,
  scrapbook: null,
  credits: null,
  displaySidebar: true,
  articleNext: null,
  articlePrevious: null,
  timeline: null,
  prompt: null,
  gallery: null,
  articleParent: null,
  block: null,
  orgchart: null,
  showSeeded: false,
  webhookUpdate: false,
  communityUpdate: false,
  commentPlaceholder: null,
  passcodecta: null,
  metaTitle: null,
  metaDescription: null,
  subheading: null,
  coverIsMap: false,
  isFeaturedArticle: false,
  isAdultContent: false,
  isLocked: false,
  allowComments: true,
  allowContentCopy: false,
  showInToc: true,
  isEmphasized: false,
  displayAuthor: false,
  displayChildrenUnder: true,
  displayTitle: true,
  displaySheet: true,
  competitionEntries: [
    {
      id: 747844,
      title: "untitled",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "CompetitionEntry",
      icon: "fa-solid fa-balloon",
      url: null,
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
  ],
  badge: null,
  fans: [
    {
      id: "22ec05dd-dd6a-4a03-b3d5-8f0c1ecddf16",
      title: "R. R. LoreCastle",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/R.%20R.%20LoreCastle",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "3bfd59ab-0dbe-4015-ac07-4c322cb6e685",
      title: "Serukis",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Serukis",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "4998e3f5-9192-4c78-9f61-c9df26b3fe2e",
      title: "Alishahr",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Alishahr",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "4ec5a618-4110-49c4-8da4-7bb44c469395",
      title: "Keon Croucher",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Keon%20Croucher",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "51deed93-785e-49e2-abc7-fc8cc7d5ad8c",
      title: "TheDumbOwl",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/TheDumbOwl",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "538556cd-3a86-43f1-88cf-17f15084352a",
      title: "Mochimanoban",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Mochimanoban",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "576b53bd-7501-4a33-b759-a8e294df7342",
      title: "Paul Norris",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Paul%20Norris",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "702fe4c6-fdde-4afb-82b6-f52c5c593e0c",
      title: "AmélieIS",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Am%C3%A9lieIS",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "7480083c-abf6-43a7-98d9-dfce50883dd3",
      title: "ValentineDM",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/ValentineDM",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "8b9236ea-315c-4c39-9c1c-c46f05e2b221",
      title: "Kefkejaco",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Kefkejaco",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "950fc1d9-8a14-4337-9a3e-4eefedc4b718",
      title: "kitoypoy",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/kitoypoy",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "b57cd04e-08c3-4534-abff-b4e530fd3a69",
      title: "Dazzlinkat",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Dazzlinkat",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "c0c3319e-3f5c-4719-a806-a4919e6f1966",
      title: "Kat Chiron",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Kat%20Chiron",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "c8fa2d22-bb7d-40de-9979-727655073e76",
      title: "CrazyEddie",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/CrazyEddie",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "d7bbd35b-a7af-4584-a379-b1a6b74b3911",
      title: "Kittymonster",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Kittymonster",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "dc70b068-2a03-4643-8364-6ba7b5c8da98",
      title: "Yelrafekim",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Yelrafekim",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "f020e114-3f07-4211-aeb1-90e025aa8d2e",
      title: "notahumanhand",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/notahumanhand",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "f02e44e0-02b5-4c1a-b917-3274c289b369",
      title: "SorceressLily",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/SorceressLily",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "f5f1852b-d894-473f-b79e-3e35c9597369",
      title: "JoellaKay",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/JoellaKay",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "f7226d87-fab6-474a-932f-90d41374f52e",
      title: "LiaFelis",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/LiaFelis",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "fc5e6948-fd6e-4e2f-ad60-d688f7dc13fa",
      title: "Stormbril",
      slug: null,
      state: null,
      isWip: null,
      isDraft: null,
      entityClass: "User",
      icon: "fa-solid fa-user",
      url: "https://www.worldanvil.com/author/Stormbril",
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
  ],
  comments: [
    {
      id: "4b3b8307-def9-4d72-902e-b6580ba1e4c2",
      title: "untitled",
      slug: null,
      state: "public",
      isWip: null,
      isDraft: null,
      entityClass: "Comment",
      icon: "fa-solid fa-comment",
      url: null,
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "8fef089a-69d2-4bf8-a9cb-1839517a3804",
      title: "untitled",
      slug: null,
      state: "public",
      isWip: null,
      isDraft: null,
      entityClass: "Comment",
      icon: "fa-solid fa-comment",
      url: null,
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "16bb9b65-24a9-45df-b229-269d44c09f6f",
      title: "untitled",
      slug: null,
      state: "public",
      isWip: null,
      isDraft: null,
      entityClass: "Comment",
      icon: "fa-solid fa-comment",
      url: null,
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "86b57659-8e3c-45d6-be4a-7fe642033a5c",
      title: "untitled",
      slug: null,
      state: "public",
      isWip: null,
      isDraft: null,
      entityClass: "Comment",
      icon: "fa-solid fa-comment",
      url: null,
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
    {
      id: "fa79bdb2-e2b7-405c-9926-22ac71d49fb3",
      title: "untitled",
      slug: null,
      state: "public",
      isWip: null,
      isDraft: null,
      entityClass: "Comment",
      icon: "fa-solid fa-comment",
      url: null,
      subscribergroups: [],
      folderId: null,
      tags: null,
      updateDate: null,
    },
  ],
  character: null,
  editURL:
    "https://www.worldanvil.com/world/person/52664451-feec-46c7-aa60-765bba87944d/edit",
  firstname: "Kailuva",
  lastname: "Sikuvael",
  middlename: null,
  maidenname: null,
  nickname: null,
  honorific: "Wanderer",
  suffix: "of the Mountain's Eyes",
  dobDisplay: null,
  dob: "5351",
  dod: null,
  dodDisplay: null,
  age: null,
  circumstancesBirth: "Middle of an eclipse",
  circumstancesDeath: null,
  pronouns: "he/him",
  eyes: "Dark teal, round",
  hair: "Messy and pale blue",
  skin: "Pale white",
  height: "6'6",
  birthplace: "@[Mt Firanthul](location:ddb13ca3-8197-4a55-bcf7-0a2e12f08265)",
  deathplace: null,
  residence:
    "@[The Tower of Sathelis](settlement:4aec5ad0-3a70-4b5e-981c-7007477118e1)",
  weight: null,
  gender: "Male",
  speciesDisplay: null,
  physique:
    "[row]\r\n[container:col-md-4]\r\n[container:art-pic]\r\n[img:4699454]\r\n[/container]\r\n[/container]\r\n[container:col-md-8]\r\nKailuva is a tall and not particularly muscular elf who nonetheless possesses fantastic dexterity, which he relies on greatly every time he manages to walk into just about every trap in a dungeon. He barely shows his age, like many elves, except in his loud complaints about not being able to get around so easily anymore and in how he'll often be found riding his wife's wolves around instead of making the walk himself. \r\n\r\nHe wears a number of scars as proof of his travels, most significant among them being the white scar over one eye that marks his status as one watched over by the desert's draconic population - not that he's wholly certain what that means or entails. He's also begun decorating his arms with similar tattoos to his wife, infused with magic just the same as hers.\r\n\r\nThese decorations paint the story of his life onto his arms, celebrating his adventures and misadventures, his love, and the three children of whom he is ardently proud.\r\n[/container]\r\n[/row]",
  bodyFeatures: null,
  facialFeatures: null,
  identifyingCharacteristics: null,
  quirksPhysical: null,
  perceptionPhysical: null,
  specialAbilities: null,
  clothing: null,
  items: null,
  characterPrototype: null,
  rpgAlignment: "Chaotic Good",
  deity:
    "@[The Elven Pantheon](organization:e4a39184-ae5b-4fc2-9a77-a6387a3aba77)",
  currentstatus: null,
  history:
    "[quote]You know, this is going to be a good two centuries - almost three - of information. That's a lot. Sure you don't want to come help me figure out if this explodes instead?|Kailuva[/quote]\r\n\r\nKailuva was born in the isolated @[Nisrei](organization:5177657a-0219-4b38-ae53-0f19254114e2) settlement of Mount Firanthul at a particularly inauspicious time - when his mother finally delivered him after a lengthy labour, the moon was blotted out by a lunar eclipse. Later in life, when his luck began to manifest, this was generally considered to be a result of this eclipse.\r\n\r\nLike most of the Nisrei, Kailuva wasn't permitted to leave the confines of their mountain home until he was a teenager as a safety precaution against the rough winter wilds. He spent much of his childhood assisting in construction efforts and farming, and developed a love for finding out new strange facts about the areas in which he worked.\r\n\r\n[row]\r\n[container:col-md-8]\r\nAs he aged, he began to talk more and more about all of what he'd learnt, and the Nisrei elders took note of his bright spirit and strong communication skills. By the time he was due to take his walk on the @[Unguided Path](ritual:e09d03e3-e241-4048-8c83-27b36fe5df6b), Kailuva was well-known across the entire Nisrei settlement and had been steadily working on befriending every trader who came by.\r\n\r\nShortly after he returned from the Walk, with a fair few new scars and now recognised as an adult by snow elven society, Kailuva began to petition to be allowed to venture out of the mountain settlement. He started off small as a hunter, but soon began carrying news to nearby settlements on behalf of his fellows. Over time, this expanded into a formal role as a diplomat and eventual trips to other nations of Iskaldhal.\r\n\r\nHe is known well for being one of few snow elves to survive discussions with the @[draconic](species:22cbf112-d115-4105-bbf5-27e7c52a1940) life around @[Kylmävikk Desert](location:d916ae3b-5d92-4949-8f61-c061102fb05f); the white scar running down his right eye is a gift from one, and stands as a warning to others to leave him alone.\r\n[/container]\r\n[container:col-md-4]\r\n[container:art-pic]\r\n[img:4699450]\r\n[/container]\r\n[/container]\r\n[/row]\r\n\r\nHe met Tuiravi in the middle of one of his journeys out. He'd been tasked with investigating @[Isyrei](organization:a3c239ea-ef2b-47df-a48d-5bc87f9e9c78) rumours of a distant settlement at the edge of the known world, @[Guided Breath](settlement:8fd95620-e4ec-49bf-9c2b-5ce1e281e6a9), and things had naturally gone horribly wrong when an unexpected leystorm had spun up.\r\n\r\nHe'd set up a small shelter beneath a jagged outcropping, protected by his own powers, but it was only a few hours after he'd settled in to wait out the storm that the outcropping [i]moved[/i] beneath him, and the dragon that had been resting in the snow flung him off as it took flight. Luckily for the wayward traveller and diplomat, Tuiravi had been investigating disturbances in the leylines nearby, and heard his yell. \r\n\r\n[row]\r\n[container:col-md-4]\r\n[container:art-pic]\r\n[img:4699453]\r\n[/container]\r\n[/container]\r\n[container:col-md-8]\r\nThey had plenty time to talk on the wolfback trip back to civilisation. Enough time to start flirting with one another, and feel the beginning stirrings of love. They found ways to run into eachother, after that, and eventually Kailuva proposed that they make their arrangement permanent.\r\n\r\nWhilst Tuiravi was overjoyed, she offered Kailuva a warning: she was the daughter of one of the @[Querei](organization:e7f91622-b816-4975-af3a-918d28fc8abf)'s elders, and her parent would inevitably test Kailuva on his trustworthiness and general worth before they could be wed.\r\n\r\nShe hadn't been lying. The next four years of Kailuva's life were made into a personal hell by Tuiravi's only living parent. Kailuva's mother turned on Tuiravi as soon as they met her, too, decrying her behind her back as a southern witch who wanted to corrupt their son.\r\n\r\nThe duo, fed up with the treatment, snapped.\r\n[/container]\r\n[/row]\r\n\r\nKailuva declared before his tribe that he was leaving to marry his beloved and stay with her in Sathelis, and though Tuiravi never went into detail on [i]how[/i] she dealt with her parent, the constant testing from them stopped abruptly.\r\n\r\nFor Kailuva, this was a far greater transition: the Nisrei were isolationist, and to leave to move elsewhere was to abandon the tribe. Yet this would not be the case for him.\r\n\r\nThe Nisrei elders summoned him and spoke to him at length, and he left the mountain with the role of being the @[Mountain's Eyes](profession:551e2258-31eb-4c3a-9b92-a555bf8430e1). He was to explore, to see new things, and to bring back knowledge to the tribe when he could - to be their eyes outside their own borders, to take on the burden of being known.\r\n\r\n[row]\r\n[container:col-md-8]\r\nIt was to be a more secretive role - in official wording, he'd be referred to as their ambassador alone - but one that both he and Tuiravi were overjoyed with. \r\n\r\nIt certainly made life easier when their first child arrived, to have that stability - even as Kailuva had to venture out on explorations on occasion. He often found himself joined by Querei and Isyrei travellers curious about his bad luck, or even by Vaeltajat who'd been visiting the Tower of Sathelis.\r\n\r\nAs each year passed with new discoveries, he began to find ways to wrestle his horrendous luck into new ways to end up in interesting, fruitful expeditions that [i]usually[/i] didn't involve him getting trapped somewhere weird (though he doesn't like to admit how many times Tuiravi and her parent have had to pull him out of the worst situations).\r\n\r\nAnd with his eldest reaching adulthood and the Querei's general acceptance of him, he had more helpers than ever.\r\n[/container]\r\n[container:col-md-4]\r\n[container:art-pic]\r\n[img:4699452]\r\n[/container]\r\n[/container]\r\n[/row]\r\n\r\nIn his older age, he has settled down somewhat in how much he travels, and sends apprentices out into the world on his behalf. This gets him the information he needs for his role, aids young Querei adventurers in getting their experience, and more importantly - prevents his luck from impacting the expeditions too greatly! His eldest daughter often tags along on these expeditions, especially when they are to other continents, and his son intends to join her as soon as he can.",
  employment: null,
  achievements: null,
  failures: "[quote]Gods, too many!|Kailuva[/quote]",
  mentalTraumas: null,
  intellectualCharacteristics: null,
  morality: null,
  taboos: null,
  presentation: "Masculine",
  sex: null,
  sexuality:
    "[quote]I mean, we're monogamous, so... does it matter?|Kailuva[/quote]\r\n\r\nLike most elves, Kailuva's sexuality is fluid. If asked, he'll describe himself as having no eyes for anyone other than his beloved Tuiravi. As he prefers monogamous relationships, he refers to her as the only one that matters to him, preference-wise.",
  genderidentity: null,
  education: null,
  languages: null,
  quotes: null,
  motivation: null,
  savviesIneptitudes: null,
  likesDislikes: null,
  virtues: null,
  vices: null,
  quirksPersonality: null,
  hygiene: null,
  representationLegacy: null,
  relations: null,
  family: null,
  religion: null,
  titles: null,
  socialAptitude: null,
  mannerisms: null,
  hobbies: null,
  speech: null,
  wealth: null,
  classification: null,
  domains: null,
  codes: null,
  holysymbols: null,
  tenets: null,
  goals: null,
  holidays: null,
  artifacts: null,
  ggmtitle: null,
  ggmjob: null,
  ggmgoal: null,
  ggmuse: null,
  ggmgoaladditional: null,
  ggmquirk: null,
  ggmequipment: null,
  ggmtype: null,
  ggmsubtype: null,
  ggmlikeability: null,
  ggmcompetence: null,
  ggmproactivity: null,
  ggmcoolness: null,
  ggmdesire: null,
  ggmfear: null,
  ggmwhyfollowing: null,
  ggmbiography: null,
  ggmdescfacial: null,
  ggmdescspeech: null,
  ggmdescbody: null,
  ggmdescsight: null,
  ggmdescsound: null,
  ggmdescsmell: null,
  ggmdesctouch: null,
  ggmdescemotional: null,
  ggmdeschappy: null,
  ggmdescsad: null,
  ggmdescangry: null,
  reign: null,
  datasheet: null,
  vehicle: null,
  parentBiological1: null,
  parentBiological2: null,
  parentAdopting1: null,
  parentAdopting2: null,
  parentSurrogate: null,
  church: null,
  realm: null,
  organization: {
    id: "5177657a-0219-4b38-ae53-0f19254114e2",
    title: "Nisrei",
    slug: "nisrei-organization",
    state: "public",
    isWip: true,
    isDraft: false,
    entityClass: "Organization",
    icon: "ra ra-diamond",
    url: "https://www.worldanvil.com/w/istralar-hanhula/a/nisrei-organization",
    subscribergroups: [],
    folderId: "1c57dce5-a8d2-4e64-ba79-cc82f0749fa5",
    tags: "stub,tribes,continents-north,origins-snwelvn",
    updateDate: {
      date: "2024-01-15 02:27:57.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  familyorganization: null,
  ethnicity: {
    id: "4196c7ca-6679-46b7-a36e-c6ed8be75b3d",
    title: "Snow Elf",
    slug: "snow-elf-article",
    state: "public",
    isWip: true,
    isDraft: false,
    entityClass: "Ethnicity",
    icon: "far fa-snowflake",
    url: "https://www.worldanvil.com/w/istralar-hanhula/a/snow-elf-article",
    subscribergroups: [],
    folderId: "-1",
    tags: "",
    updateDate: {
      date: "2024-01-15 05:46:10.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  species: {
    id: "a87bc4de-aa3e-4452-82f5-2d14e011a111",
    title: "Elf",
    slug: "elf-article",
    state: "public",
    isWip: true,
    isDraft: false,
    entityClass: "Species",
    icon: "fa-solid fa-file",
    url: "https://www.worldanvil.com/w/istralar-hanhula/a/elf-article",
    subscribergroups: [],
    folderId: "378909db-1955-4fe1-9597-7fda4b6a5c5c",
    tags: "playable,types-hmanoid,origins-elvn",
    updateDate: {
      date: "2023-10-20 21:15:59.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  currentLocation: null,
  professions: [
    {
      id: "551e2258-31eb-4c3a-9b92-a555bf8430e1",
      title: "Mountain's Eyes",
      slug: "mountain-s-eyes-profession",
      state: "public",
      isWip: true,
      isDraft: false,
      entityClass: "Profession",
      icon: "ra ra-telescope",
      url: "https://www.worldanvil.com/w/istralar-hanhula/a/mountain-s-eyes-profession",
      subscribergroups: [],
      folderId: "9191bfa7-038a-4865-a11d-ef3889f19819",
      tags: "sc2023",
      updateDate: {
        date: "2024-01-15 06:18:07.000000",
        timezone_type: 3,
        timezone: "Europe/London",
      },
    },
  ],
  relatedorganizations: [
    {
      id: "e7f91622-b816-4975-af3a-918d28fc8abf",
      title: "Querei",
      slug: "querei-organization",
      state: "public",
      isWip: true,
      isDraft: false,
      entityClass: "Organization",
      icon: "fa-solid fa-shield-quartered",
      url: "https://www.worldanvil.com/w/istralar-hanhula/a/querei-organization",
      subscribergroups: [],
      folderId: "1c57dce5-a8d2-4e64-ba79-cc82f0749fa5",
      tags: "stub,tribes,origins-snwelvn,continents-north",
      updateDate: {
        date: "2023-11-06 13:29:59.000000",
        timezone_type: 3,
        timezone: "Europe/London",
      },
    },
  ],
  isEditable: true,
  success: true,
};

export const ArticlesToTest = [KailuvaStructure];
