import { ArticleFieldConfig } from "../EditComponents/article-edit-field-renderer";
import {
  createCommonBodyFieldRegistry,
  createCommonFooterFieldRegistry,
  createCommonSidebarFieldRegistry,
  createCommonSubtitleFieldRegistry,
  createCommonDesignFieldRegistry,
} from "../EditComponents/article-edit-registry-common";
import { Document } from "@/components/types/article-types/document";

export type DocumentBodySubTabConfig = {
  eventKey: string;
  title: string;
  fields: ArticleFieldConfig<Document>[];
};

export const bodyFieldRegistry: ArticleFieldConfig<Document>[] = [
  ...createCommonBodyFieldRegistry<Document>(),
  {
    key: "body-purpose",
    kind: "bbcode",
    fieldIdentifier: "purpose",
    label: "Purpose",
  },
];

const documentTypes = [
  "Announcement, Invitation",
  "Announcement, RSVP",
  "Certificate, Civil",
  "Certificate, Professional",
  "Certificate, Education (Degree)",
  "Contract, Private",
  "Contract, Civil",
  "Decree, Royal",
  "Decree, Religious",
  "Decree, Governmental",
  "Entertainment, Game",
  "Entertainment, Generic",
  "Entertainment, Movie",
  "Entertainment, Show",
  "Entertainment, Series",
  "Guide, Generic",
  "Guide, Survival",
  "Guide, How-to",
  "Identification, Private",
  "Identification, Civil (Passport/ID Card)",
  "Imagery, Artistic",
  "Imagery, Religious",
  "Imagery, Graphic Novel / Comic Book",
  "Journal, Personal",
  "Journal, Scientific",
  "Journal, Medical",
  "Leaked Original",
  "Licence, Civil",
  "Licence, Professional",
  "Licence, Private (Letter of Marque)",
  "Manual, Professional Skills",
  "Manual, Military",
  "Manual, Artistic",
  "Manual, Martial Art / Combat",
  "Manual, Culinary",
  "Manual, Magical / Occult",
  "Manual, Scientific",
  "Manual, Technical / Blueprint",
  "Manual, Musical",
  "Manual, Linguistic (Lexicon)",
  "Manuscript, Religious",
  "Manuscript, Historical",
  "Manuscript, Legal",
  "Manuscript, Magical (Tome/Scroll)",
  "Manuscript, Musical",
  "Manuscript, Artistic",
  "Manuscript, Literature",
  "Map, Geological",
  "Map, Geopolitical",
  "Map, Topographic",
  "Map, Survey",
  "Map, Military",
  "Map, Historical",
  "Map, Weather",
  "Map, Economic",
  "Map, Star chart",
  "Map, Thematic",
  "Map, Artistic",
  "Map, Atlas",
  "Map, Floorplan",
  "Map, Treasure",
  "Other, Flyer",
  "Other, Poster",
  "Record, Patent",
  "Record, Culinary (Menu)",
  "Record, Judicial",
  "Record, Public",
  "Record, Financial (Bill, Invoice, Fine etc)",
  "Record, Deed",
  "Record, Title",
  "Record, Employment",
  "Record, Historical",
  "Record, Musical (Music, Sheet)",
  "Record, Memo",
  "Record, Logbook",
  "Record, Business Accounts",
  "Record, Research Notes",
  "Record, Transcript (Communication)",
  "Report, Civil",
  "Report, Military",
  "Report, Scientific",
  "Report, Intelligence",
  "Report, Financial",
  "Report, Manifest",
  "Report, Incident",
  "Statement, Political (Manifesto)",
  "Statement, Financial",
  "Statement, Inscription / Graffiti",
  "Statement, Artistic",
  "Study, Scientific",
  "Study, Artistic",
  "Study, Historical",
  "Study, Magical",
  "Study, Religious",
  "Text, Religious",
  "Text, Philosophical",
  "Text, Literary (Novel/Poetry)",
  "Text, Legislative",
  "Text, Letter",
  "Text, Literature",
  "Text, Newspaper",
  "Text, Magazine",
  "Textbook",
  "Treaty, Diplomatic",
  "Treaty, Trade",
  "Warrant, Royal",
  "Warrant, Civil",
  "Warrant, Arrest",
  "Warrant, Wanted / Search",
];

const mediumDropdown = [
  "Analog Recording, Audio",
  "Analog Recording, Video",
  "Canvas",
  "Clay",
  "Collage / Various",
  "Crystal, Photonic",
  "Crystal, Magical",
  "Crystal, Psionic",
  "Digital Recording, Text",
  "Digital Recording, Audio",
  "Digital Recording, Video",
  "Digital Recording, Various",
  "Digital, Holographic",
  "Embroidered",
  "Glass / Stained Glass",
  "Invisible",
  "Metal",
  "Organic",
  "Oral Tradition / Word of Mouth",
  "Paper",
  "Papyrus",
  "Psionic",
  "Stone",
  "Vellum / Skin",
  "Wood",
];

export const bodySubTabRegistry: DocumentBodySubTabConfig[] = [
  {
    eventKey: "structure",
    title: "Document Structure",
    fields: [
      {
        key: "body-clauses",
        kind: "bbcode",
        fieldIdentifier: "clauses",
        label: "Clauses",
      },
      {
        key: "body-caveats",
        kind: "bbcode",
        fieldIdentifier: "caveats",
        label: "Caveats",
      },
      {
        key: "body-textreferences",
        kind: "bbcode",
        fieldIdentifier: "textreferences",
        label: "References",
      },
      {
        key: "body-publicity",
        kind: "bbcode",
        fieldIdentifier: "publicity",
        label: "Publication Status",
      },
      {
        key: "body-legality",
        kind: "bbcode",
        fieldIdentifier: "legality",
        label: "Legality",
      },
    ],
  },
  {
    eventKey: "historicalDetails",
    title: "Historical Details",
    fields: [
      {
        key: "body-background",
        kind: "bbcode",
        fieldIdentifier: "background",
        label: "Background",
      },
      {
        key: "body-history",
        kind: "bbcode",
        fieldIdentifier: "history",
        label: "History",
      },
      {
        key: "body-publicreaction",
        kind: "bbcode",
        fieldIdentifier: "publicreaction",
        label: "Public Reaction",
      },
      {
        key: "body-legacy",
        kind: "bbcode",
        fieldIdentifier: "legacy",
        label: "Legacy",
      },
      {
        key: "body-term",
        kind: "bbcode",
        fieldIdentifier: "term",
        label: "Term",
      },
    ],
  },
  {
    eventKey: "sidebar-details",
    title: "Sidebar Details",
    fields: [
      {
        key: "body-type",
        kind: "field-dropdown",
        fieldIdentifier: "type",
        label: "Type",
        options: documentTypes,
      },
      {
        key: "body-medium",
        kind: "field-dropdown",
        fieldIdentifier: "medium",
        label: "Medium",
        options: mediumDropdown,
      },
      {
        key: "body-relatedlocation",
        kind: "dropdown",
        fieldIdentifier: "relatedlocation",
        label: "Related Location",
        entityClass: ["Location"],
      },
      {
        key: "body-myth",
        kind: "dropdown",
        fieldIdentifier: "myth",
        label: "Myth",
        entityClass: ["Myth"],
      },
      {
        key: "body-documentauthors",
        kind: "dropdown",
        fieldIdentifier: "documentauthors",
        label: "Document Authors",
        entityClass: ["Person"],
        isMulti: true,
      },
      {
        key: "body-signatorycharacters",
        kind: "dropdown",
        fieldIdentifier: "signatorycharacters",
        label: "Signatory Characters",
        entityClass: ["Character"],
        isMulti: true,
      },
      {
        key: "body-signatoryorganisations",
        kind: "dropdown",
        fieldIdentifier: "signatoryorganisations",
        label: "Signatory Organisations",
        entityClass: ["Organization"],
        isMulti: true,
      },
    ],
  },
  {
    eventKey: "body-documentContent",
    title: "Document Contents",
    fields: [
      {
        key: "body-contents",
        kind: "bbcode",
        fieldIdentifier: "contents",
        label: "Contents",
      },
    ],
  },
];

export const subtitleFieldRegistry: ArticleFieldConfig<Document>[] = [
  ...createCommonSubtitleFieldRegistry<Document>(),
];

export const sidebarFieldRegistry: ArticleFieldConfig<Document>[] = [
  ...createCommonSidebarFieldRegistry<Document>(),
];

export const footerFieldRegistry: ArticleFieldConfig<Document>[] = [
  ...createCommonFooterFieldRegistry<Document>(),
];

export const designFieldRegistry: ArticleFieldConfig<Document>[] = [
  ...createCommonDesignFieldRegistry<Document>(),
];
