import { Article } from "../article";
import { Image } from "../image";
import { Location } from "./location";
import { Person } from "./person";
import { Species } from "./species";

export type Organisation = Article & {
    motto: string | null;
    publicAgenda: string | null;
    alternativeNames: string | null;
    demonym: string | null;
    assets: string | null;
    structure: string | null;
    history: string | null;
    disbandment: string | null;
    demographics: string | null;
    veterancy: string | null;
    trainingLevel: string | null;
    governmentsystem: string | null;
    powerstructure: string | null;
    economicsystem: string | null;
    legislative: string | null;
    judicial: string | null;
    executive: string | null;
    gazetteer: string | null;
    currency: string | null;
    territory: string | null;
    military: string | null;
    religion: string | null;
    technology: string | null;
    foreignrelations: string | null;
    laws: string | null;
    culture: string | null;
    imports: string | null;
    exports: string | null;
    agricultureAndIndustry: string | null;
    tradeAndTransport: string | null;
    education: string | null;
    infrastructure: string | null;
    mythos: string | null;
    origins: string | null;
    cosmology: string | null;
    tenets: string | null;
    priesthood: string | null;
    ethics: string | null;
    divinepowers: string | null;
    intrigue: string | null;
    worship: string | null;
    sects: string | null;
    foundingDate: string | null;
    dissolutionDate: string | null;
    showDiplomacy: false;
    capital: Location | null;
    geographicLocation: Location | null;
    parent: string | null;
    statereligion: Organisation | null;
    type: string | null;
    formation: string | null;
    leader: Person | null;
    familyleader: Person | null;
    headofstate: Person | null;
    leadertitle: string | null;
    headofgovernment: Person | null;
    rulingorganization: Organisation | null;
    belligerents: Organisation[];
    neighbors: Organisation[];
  };