import { Article } from "../article";
import { Location } from "./location";

export type Species = Article & {
    trinominal: string | null;
    ancestry: string | null;
    lifespan: string | null;
    anatomy: string | null;
    perception: string | null;
    genetics: string | null;
    ecology: string | null;
    diet: string | null;
    domestication: string | null;
    uses: string | null;
    biocycle: string | null;
    growthrate: string | null;
    symbiotic: string | null;
    isSentient: boolean;
    isIntelligent: boolean;
    geographicalOrigin: string | null;
    averageIntelligence: string | null;
    averagePhysique: string | null;
    facialCharacteristics: string | null;
    skinHairColor: string | null;
    traits: string | null;
    averageHeight: string | null;
    averageWeight: string | null;
    averageLength: string | null;
    namingTraditions: string | null;
    firstnamesMale: string | null;
    firstnamesFemale: string | null;
    lastnames: string | null;
    majorReligions: string | null;
    majorOrganizations: string | null;
    beautyIdeals: string | null;
    genderIdeals: string | null;
    courtshipIdeals: string | null;
    relationshipsIdeals: string | null;
    technologicalLevel: string | null;
    languages: string | null;
    etiquette: string | null;
    dresscode: string | null;
    culture: string | null;
    customs: string | null;
    taboos: string | null;
    history: string | null;
    socialstructure: string | null;
    mythsAndLegends: string | null;
    historicalFigures: string | null;
    interspeciesRelations: string | null;
    isExtinct: boolean;
    conservation: string | null;
    behaviour: string | null;
    datasheet: string | null;
    discoverer: string | null;
    locations: Location[];
}