services:
- type: web
  name: brigidsanvil
  runtime: node
  plan: starter
  buildCommand: npm install; npm run build
  startCommand: npm start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production 