import { LocationType } from "../location";

export const LocationTypes: LocationType[] = [
  {
    id: "5ffde82f-01ad-4e87-959a-48a3009bd51b",
    title: "Abyss",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "040b66e7-568e-4abc-85e1-1d65df5427be",
    title: "Air mass",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1d07845a-9948-4a8c-a453-7efd0efb4341",
    title: "Archipelago",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "41e3c214-3c48-4cbc-ab4e-6d1293602fe2",
    title: "Asteroid",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "734d612e-6331-4115-b5ee-00d8ff3c6f8e",
    title: "Asteroid belt",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c26a1dad-b3a7-4359-8c8f-f19882a01f35",
    title: "Atmospheric trough",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0d78e713-ab43-41fe-a35a-1673a2a60030",
    title: "Atoll, Underwater",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "83702895-31d2-4b84-a6a7-21f84ce050a9",
    title: "Badlands",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "55624004-48ed-471a-a1cb-ecef22d351ae",
    title: "Bay",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ce91d6f1-7364-47e4-bc50-37a6c2ac84d5",
    title: "Black Hole",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "71a5a53d-1a42-430d-b6a8-0fa4dc85bc4b",
    title: "Bodden",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2490acee-1613-4db7-b2a4-8c678f9fd6de",
    title: "Brush",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1c8b4f9a-4e75-43ec-91ba-9a79e2d41ed7",
    title: "Canyon",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "01b0da81-dfb9-42b1-8337-31c330627ea3",
    title: "Cape",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0e1b66e4-6364-432f-b39f-11200f32ae10",
    title: "Cave",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "32070242-2f51-4204-9d75-a87666ff1ce6",
    title: "Cave System",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7f227f80-7385-4be5-859c-f2c6a90d8719",
    title: "Chasm, Underwater",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1849bb33-3ce0-4a84-85af-540ec2c3d4a2",
    title: "Cliff",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2cd3f81d-2c4c-4f7a-b0ca-6a4e9a3a3a4f",
    title: "Cloud band",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2d5f46d0-a93c-450f-9f4d-914cc37f9a55",
    title: "Coast / Shore",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2ce46971-5996-4aaf-a2d5-d0c65a4f9fca",
    title: "Continent",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "109501e4-6409-4fff-a8ab-b303a33b4bc9",
    title: "Copse",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "60995454-8702-4a46-8ec4-76045f21ef28",
    title: "Coral Reef, Atoll",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d8a2fa95-b092-4679-bf03-d6ca6630a973",
    title: "Coral Reef, Barrier",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "05348121-94f6-4d2c-8a34-0c697318960b",
    title: "Coral Reef, Fringing",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ac15d3c4-423a-4a23-a74f-c42cb9adadd5",
    title: "Coral Reef, Platform",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "90d7c673-8c7f-4ab9-bb32-d55b8f0db6b8",
    title: "Cove",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "3224e3b8-aba9-470f-bcfa-1df9c807e17d",
    title: "Cracked Planet",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0252da4f-a19d-4772-ab0a-c1ca6902bab9",
    title: "Crater / Crater Lake / Caldera",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "dba2322c-3aac-4a7b-a37e-9540967d3797",
    title: "Current",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0e89b6cf-cca5-43fe-b1ef-201f20f7a6df",
    title: "Desert",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "da92d2aa-1853-4749-97ed-d9961ab9ca7d",
    title: "Desert, Ice",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ee4551a1-fe4b-4553-8e78-139a565a3376",
    title: "Dimensional plane",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c9f2ded2-a684-4dfe-818d-4c181f3b1180",
    title: "Dimensional, Pocket",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8877c6fa-ab62-4576-906e-21f8e862cfd9",
    title: "Doldrum",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f64bae2d-a6dc-447a-aacb-55ddf9f63cdd",
    title: "Downwelling",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ac72ccb0-d61b-4a4c-9f97-c430076a2e92",
    title: "Dune",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "261e88a8-568c-4e04-a69f-0e4110947047",
    title: "Estuary / River delta",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "30935880-e099-4dcf-9f5e-a7730c75e7af",
    title: "Expanse",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c2c3e092-0ec1-4355-b12d-d87ca21c1bb5",
    title: "Field",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "52d36b61-d84d-4030-bc06-cca1a5e57b7d",
    title: "Fjord",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "51027675-7bee-4179-ba69-5e2abc31dd26",
    title: "Forest",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "568d6a7b-cd93-4775-a9cb-b6a469038792",
    title: "Forest, Boreal (Coniferous)",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5a16f4f0-5bbc-4e59-8562-1f63c7faf254",
    title: "Forest, Cloud / Water (Subtropical)",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4b69d15e-fb1f-4f11-b13d-2bd03b27038a",
    title: "Forest, Jungle (Tropical)",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7339b2ae-61d6-489e-8f86-86d99be77dfd",
    title: "Forest, Temperate (Seasonal)",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "608642b4-a986-49b9-b0ef-5ee7c3d07c67",
    title: "Galactic Nebula",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "fd300b84-fc85-43fe-9e5f-92067c59fd64",
    title: "Galactic Quadrant",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9833f867-65b8-4e35-9b64-833ea441b328",
    title: "Galactic Sector",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ee86ab3c-4057-46e4-9584-b7980464e025",
    title: "Galaxy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "65cf3eda-7099-479b-9901-693174b65a78",
    title: "Galaxy Cluster",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "3d138252-d415-4f6a-8641-9a98cdad0cd1",
    title: "Galaxy Supercluster",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0278daee-9402-4b5d-9d32-d6a1751181f7",
    title: "Glacier",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "86a30cb5-4286-4f05-8379-c2c3407d8105",
    title: "Gorge / Rift",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "91435819-1f95-46b4-aab5-f6aff7b3f8db",
    title: "Grassland",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "86889ed0-c829-4614-bba0-a4863198cb5d",
    title: "Grove",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "aeec6efc-7d57-435f-b9c1-c97a11b5e852",
    title: "Gulf / Lagoon",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b9bfd50f-026a-4908-af3e-2e64be6db264",
    title: "Gyre",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "51003f69-0974-4b94-b3c5-fe223b8eb14e",
    title: "Highlands",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "35841f1c-31a6-4ad6-b7ee-c3d7cc5e521a",
    title: "Inland Sea",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "3ad65a5f-1578-4527-a485-190136ff5477",
    title: "Island",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "497b1935-c230-4fbc-ae3d-3f29eafe8b1c",
    title: "Island, Floating",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "20ac05dd-a8c3-4ce5-9d05-f58cf3c32659",
    title: "Isthmus",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4c362f6a-ed10-42f9-8e5f-ec8633c76419",
    title: "Jet stream",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f5f0d6c4-831b-466c-99c9-7dcdb516904c",
    title: "Jungle",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d13e710a-df83-44dd-b588-08975674528e",
    title: "Lake",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "50045ef8-fae2-4034-9885-78f4cc0dd314",
    title: "Lake, Dry",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e98d9536-0cdd-4b42-9e6e-38d5cea1947f",
    title: "Landmass",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4ecd7eb7-63da-4b33-be83-1113a509c568",
    title: "Lava river",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b87e8997-1c7f-408f-9fdb-3f164cde292e",
    title: "Magical Realm",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f08ac4a6-86ad-48f6-b350-426065352890",
    title: "Meadow",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8c389b7a-640f-4fb7-b199-580ea2568b7f",
    title: "Megastructure",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "de9b30da-18ee-49cd-b822-2de317225dfa",
    title: "Moor",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "be328823-b0e0-43a0-9895-5e661c33c1b1",
    title: "Mountain / Hill",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "fc92d3c2-5954-452c-b146-90f090a0b636",
    title: "Mountain Pass",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e1260468-4d94-4d0e-b3fb-dc90ed4c4821",
    title: "Mountain Range",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c3b93b0b-7184-436a-a002-b97c4f7b5c7f",
    title: "Multiverse",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "98f286dc-1dc5-493c-847c-baf6a1cdc65a",
    title: "My Butt",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "398a23e6-ab6b-4da5-a83c-da98fb13d6f2",
    title: "Natural Wonder",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f5b4a6d1-cd0f-4736-bff9-7b68abefe246",
    title: "Nebula",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2deb4d3e-1f7f-4e61-a828-3e5e2e41a480",
    title: "Oasis",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "89788c22-5771-4788-90d3-fb2e2ac21313",
    title: "Ocean",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9c826b91-6558-41c2-96bd-76aeacd3cbe9",
    title: "Peninsula",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "dd633c5d-6cfc-4513-941d-4d02443799f9",
    title: "Persistent storm",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "cf6c57c2-f357-4f2b-8203-a2b435b5df57",
    title: "Plain",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "3809398e-495c-4824-840f-cf4329a2a86c",
    title: "Planar Sphere/Grouping",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "77c008bc-5897-4cbc-b256-4f2940416785",
    title: "Plane of Existence",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2cc52e77-1a1d-4d31-8dff-e2121b121530",
    title: "Planet",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7136a804-d8f4-4f55-bf3c-96995f4ef76b",
    title: "Planetary Orbit",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8dbc3428-4ebf-4f6d-afd8-e030f6eff62f",
    title: "Planetary Ring",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "da5081a2-928e-494b-9689-21647e927a56",
    title: "Planetoid",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1deb442c-ef54-449e-88bc-123b85681bbe",
    title: "Planetoid / Moon",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "76d55c71-5dbc-4eac-80f4-c4ac870b14e6",
    title: "Planetoid, Rogue",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9b0e14d9-7949-4d99-b792-fd4a61286976",
    title: "Plateau",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c8a45ead-894c-482c-99cc-aed5f03567f9",
    title: "Pocket Universe",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "332c25b2-08c9-44c2-91b0-590ca62bc97e",
    title: "Pond",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "09afeb77-5395-4aca-ba9a-bd6b118f0903",
    title: "Rapids",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "39fff512-4862-408a-a70a-ee34c5aee1fd",
    title: "Region",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9d61d04d-00a6-4905-b5d3-025e15669bb2",
    title: "River",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "84355870-2fe9-4f4e-893a-9c05b0052683",
    title: "River Basin",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "25b9da75-ac78-48e5-a0cf-38b05957a2ef",
    title: "Rock Formation",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "037c8982-178f-4d61-8719-1d092a563738",
    title: "Rolling Hills",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "49b18abb-5f2e-4749-aec8-2c180770bbcf",
    title: "Salt flat",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "cc94041c-5f2f-43d6-b93e-4036c92cb034",
    title: "Savannah",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7eeb77f8-93ab-47df-8e1b-7aa054436689",
    title: "Sea",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7546a111-9cc7-4199-b88e-5a7c11ac34b8",
    title: "Shoal",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9b538897-b111-4c6e-ac82-9de59b60d3c3",
    title: "Simulation",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "10061a16-44fb-4578-95a4-08555c22afb2",
    title: "Sinkhole",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ddcf10bf-8d64-4296-9e38-e4a195ac0469",
    title: "Solar System",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "500adf9a-4423-4475-ad15-1d4ed0d7fc36",
    title: "Space Station",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5315b8c3-a82b-497d-ba66-f8041ef9208e",
    title: "Spring",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f0d8746b-ea2b-4b6c-80e3-c5b1cbd6a03a",
    title: "Star",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "fc347707-e3cb-462f-b828-5e94644bb34e",
    title: "Star System",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4e8d6a0f-da53-4446-8225-0a7276b0def9",
    title: "Star System Sector",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "37e771de-0bbd-4e6e-b5ce-6a44cc0b5a36",
    title: "Steppe",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1be04b0c-83c2-466d-8a73-d4270106214b",
    title: "Strait",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "89201d59-cfde-449c-9fa7-db0b3cc0ad0d",
    title: "Stream",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "984e01e7-9521-485e-961a-766a343205d8",
    title: "Subcontinent",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e4a55607-3d24-417a-a15c-2315227427a5",
    title: "Summit",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c89b782f-d7e7-4055-9657-4df1a29946a9",
    title: "Supercontinent",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "aed263dd-f38c-4039-9d0c-b22478c918a9",
    title: "Taiga",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "6cc2c0f1-c47c-446e-b162-88a62274e087",
    title: "Territory",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b70c66dc-e13b-4edf-a457-2d849ecba175",
    title: "Theatre",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5068dc80-374f-4bda-8ef1-815065688483",
    title: "Tundra",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "855710a2-b0e6-4777-8035-9668b3b7a72b",
    title: "Underground / Subterranean",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4b3a6839-e9cc-4de1-9ee9-926bf577df6b",
    title: "Universe",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "90b01cb4-066e-40d1-b252-fc94e94e6d08",
    title: "Upwelling",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "771c1c1b-52e3-4833-8459-1c0b57e922a0",
    title: "Vale",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "6174c325-a418-434e-9ce4-59b1969122a1",
    title: "Valley",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "dfeb4389-9472-4a21-be38-54722c24f895",
    title: "Void",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f507bdd4-e9c9-41d3-be07-511e9f973125",
    title: "Volcano",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7b5917cc-f4c2-488b-b336-8400c3e2590f",
    title: "Volcano, Underwater",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7bdbe351-753c-4631-bdf0-35543ff7b141",
    title: "Vortex",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "75e5b8d1-31c2-4f5b-bfca-d6ddcc3971f9",
    title: "Wasteland",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "dff857da-1277-4588-84c5-a2bec095d19c",
    title: "Waterfall",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "39834bf7-c23b-4393-b86b-ccc5abbd2a61",
    title: "Wetland / Swamp",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "87c675b0-754a-42de-91db-dfd9222a92fd",
    title: "Wind belt",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "37a704ab-2967-4431-ba9f-f826cfb90a16",
    title: "Woods",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1c59c0db-1140-4e60-9be4-641bb7621504",
    title: "World",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "19e4c050-32e1-499d-b835-7881217bdc1d",
    title: "Wormhole",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
];
