import { OrganisationType } from "../organisation";

export const OrganisationTypes: OrganisationType[] = [
  {
    id: "0808138b-f14c-4608-a0d0-8374e3496bb7",
    title: "Activist, Charity",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "977edd07-0748-487d-974e-7a995fc0881f",
    title: "Adventuring Party",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8316bd69-281f-4eb0-8e7d-01fb22b0208e",
    title: "Alliance, Cultural",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b1eaedc5-f0ca-44d3-8c7a-b90b8c671bb8",
    title: "Alliance, Economic",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "67314e6a-7f7e-4788-9892-8e7c3d95c65a",
    title: "Alliance, Generic",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "75157665-8b69-4f8a-a755-1b3bf11c6dd5",
    title: "Alliance, Military",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b5fdec99-d8c9-46e9-9baa-6088d15847a7",
    title: "Broadcasting, Digital Network / Website",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "a6d5bb14-4ea5-4353-881a-2721e877eae8",
    title: "Broadcasting, Newspaper / Magazine",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0bf026fa-5a4d-403b-bd74-fcf7c9a7ecc2",
    title: "Broadcasting, Other",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "29dc032b-11cb-4b99-aac0-07626cb15c32",
    title: "Broadcasting, Radio",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e717ee45-e214-4509-ac41-a715ae27313b",
    title: "Broadcasting, Television Network",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5b06ff20-11e1-4226-8638-73df043781b0",
    title: "Civil Services",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5d5f1ee6-a353-4a03-9de6-c219b1901523",
    title: "Civilian, Crew",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "18bac74e-c5f8-4b38-b468-9be41958c6f7",
    title: "Civilian, Knightly Order",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "3b454422-b668-4907-90a6-7d800e3ef059",
    title: "Consortium, Business",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "683eb43f-8214-4fd1-b216-bf6937e88f65",
    title: "Consortium, Financial",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1c0cce7c-be12-4201-8ed5-cd49493d7ec4",
    title: "Consortium, Research",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "256b0ba4-885c-4d52-b711-67ce9663098c",
    title: "Corporation, Aerospace",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f9cf35f4-0a0b-4eb3-8416-dd0ab5ae69ec",
    title: "Corporation, Agriculture",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "efd08b1b-682f-4242-8ad7-089260ecc39d",
    title: "Corporation, Business",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b46fa9dd-6199-4d1f-b755-222ecfe574ca",
    title: "Corporation, Commerce",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ff82bf97-3774-433c-bb2d-a08fff65e1ca",
    title: "Corporation, Conglomerate",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "63832cf8-8989-478a-bd88-88ea873c3e1d",
    title: "Corporation, Construction",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5c4465e9-0bf4-4d28-a117-fc4d36f600dc",
    title: "Corporation, Education",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ec4a1ebd-d1a8-4a1f-9d6b-725a6e605cb7",
    title: "Corporation, Electronics Industry",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2c206ec7-75bd-4ceb-8aa6-8c4ac0df23c0",
    title: "Corporation, Energy Industry",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1d7c6a51-0b9c-4478-8e28-15a10614e618",
    title: "Corporation, Entertainment",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "fc83905f-48b7-4e9c-909a-33f6f56753ee",
    title: "Corporation, Finance",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "91247ea8-b068-4ec9-b8ce-a1de861bcd35",
    title: "Corporation, Financial",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0cde0259-c070-421e-91ba-e9a1d5f50a40",
    title: "Corporation, Food Industry",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "afef40d3-7f28-4e72-8492-46329493c27d",
    title: "Corporation, Hospitality",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1334a5ba-16c0-4c5d-8da2-66ca18daf397",
    title: "Corporation, Infrastructure",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9083f7f3-0cb8-4f98-b509-3e3d4fb3f5f9",
    title: "Corporation, Law Firm",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d58dfe56-af97-4d22-8d53-fb99f708a151",
    title: "Corporation, Manufacturing",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b5440d62-684e-4493-bcb8-644f44f1bddd",
    title: "Corporation, Medical",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f5f6b484-90e0-45bd-8f57-bb48d634c6a0",
    title: "Corporation, Mining/Resources",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d6786805-6d6a-494f-bc13-ef622ca883b6",
    title: "Corporation, News & Media",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "273104a7-c335-4661-8eb9-5e57b72e8c9c",
    title: "Corporation, Pharmaceutical",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "47040f85-5e9e-4ff1-9e56-db90937c95d2",
    title: "Corporation, Research & Development",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8a87245b-804c-4733-b722-2e01d23dab1d",
    title: "Corporation, Security",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0ee367aa-33f1-4e4a-a8d1-773a629bbae6",
    title: "Corporation, Telecommunication",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0a22b304-96b0-4fe9-9574-e00909e76ca3",
    title: "Corporation, Transportation",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "908059fe-a75d-4d3f-a580-9a960b83ba09",
    title: "Coterie",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1f974605-642f-4a75-90b1-eec72efa8a3f",
    title: "Court System",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0574674a-eaae-459e-8623-327883a4ba52",
    title: "Court, Noble",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "74f4324c-04dc-4216-9290-c5a1353b4da2",
    title: "Court, Royal",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0cae3037-c701-4c97-9b66-8b2bfcc84d5f",
    title: "Druidic Circle",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1d9c2a4b-318c-4ee5-9201-12938b95c398",
    title: "Education, Faculty",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0cab59d8-df13-45ad-a83d-2b53d08857ae",
    title: "Education, Magic",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "a51ef0c1-484b-41b8-bf34-ef13aad4cede",
    title: "Educational, Library",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "12acb17b-2b6e-4241-9eed-cfc222298471",
    title: "Educational, School/Academy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5a67ad40-4d76-4626-a49b-470884198177",
    title: "Educational, Scientific Institute",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "38d99d1c-4427-49d8-8c6d-5fee321b1866",
    title: "Educational, Society",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2c6dc3b8-bfe5-43e4-84a5-d318b0aa1b16",
    title: "Educational, University",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4332bfe4-ff56-456d-8cab-c2d3f72365e2",
    title: "Entertainment, Music band",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9b72f25c-249e-4fff-b3c9-d7d13286110c",
    title: "Entertainment, Sports team",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b38664fa-ecaa-4c29-b962-c73d9131fb64",
    title: "Entertainment, Troupe",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "89c169ff-39c4-498d-af0c-8da461582097",
    title: "Exotic, Gestalt Consciousness",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2574e8da-cd45-4e61-8811-66ae74725dd0",
    title: "Expedition, Colonization",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "171301bf-78b9-483b-b964-4a9ccc32c723",
    title: "Expedition, Military",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e0e5fb16-8c01-4d67-b7ae-7e6466caa7ab",
    title: "Expedition, Scientific",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "71fb6e51-2c7e-4fc8-89db-de5b9d7bdf2b",
    title: "Family",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "723a79ef-fbe8-4cef-aae7-0c26619fcf81",
    title: "Financial, Bank",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "eda9a074-4390-472f-95df-e48b747fd90e",
    title: "Financial, Merchant League",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "38daf6fd-fab5-4b70-9099-c63489cc4bf0",
    title: "Financial, Other",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "db9295ef-8f50-47f6-bc68-f04c84ac65c2",
    title: "Geopolitical, Archduchy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "509d014b-dfbb-4768-8f55-b682e6b31085",
    title: "Geopolitical, Band",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e7875bb5-4f06-477d-86cf-2099f4ec99e0",
    title: "Geopolitical, Barony",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "eb0298bf-6fa8-4a32-9dd7-cf0163133281",
    title: "Geopolitical, City council",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "dd2d4f67-c6a9-4ff4-9234-056b59a48f2e",
    title: "Geopolitical, City-state",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2903503f-230d-4a65-844a-e0652357e3ed",
    title: "Geopolitical, Clan",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9491e458-9c9e-48cb-a8da-e7b0af2e8b4e",
    title: "Geopolitical, Co-rulership",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0e694b20-f858-4bb8-b8fc-99c04412d862",
    title: "Geopolitical, Colony",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "6f80e14b-7c55-4b85-98a3-ab6912e84030",
    title: "Geopolitical, Country",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "737c9fee-859e-48b7-acd4-d0b0bbb0c480",
    title: "Geopolitical, County / March",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "089f7fb0-7d34-4dd8-8875-f925331fdfec",
    title: "Geopolitical, Duchy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f1d0eada-8b1e-407b-b092-698dee4e32cf",
    title: "Geopolitical, Empire",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "658eef81-d6c8-4ec0-af46-c7bdc491cc0e",
    title: "Geopolitical, Free City",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "29dc8d55-b604-432c-b7f9-2c6aceb93918",
    title: "Geopolitical, Great house",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "291ac377-9933-4610-9617-1584e8e96f56",
    title: "Geopolitical, Kingdom",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "aa7073ba-23a9-4c8a-88a0-25cd1ce5db86",
    title: "Geopolitical, Ladyship",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "14ca2f41-76e2-48c0-be96-ae5478f8c3a7",
    title: "Geopolitical, Lordship",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e81c0630-9c10-4248-9341-ffc10fcdf9be",
    title: "Geopolitical, Magocracy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "33a9c50e-313f-491a-b3c0-a967365521b2",
    title: "Geopolitical, Manor",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1d69c174-043c-4016-83ca-31d5f79c5a14",
    title: "Geopolitical, Marquisate",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8ca75929-ba9d-4b45-ab35-b6f1f94946e6",
    title: "Geopolitical, Nomadic tribe",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f8676338-a731-4aab-9243-4cd6b2fdd62b",
    title: "Geopolitical, Principality",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "169541d1-eb83-4924-a6ed-5768a6b6557a",
    title: "Geopolitical, Protectorate",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1c667f1e-66e9-49cb-bba7-99ab434d95ca",
    title: "Geopolitical, Province",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ba7bfab1-f746-497f-8a37-4361057c3e22",
    title: "Geopolitical, Queendom",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9d3a71c5-d175-4514-a705-d230be59087a",
    title: "Geopolitical, Republic",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ab5ab16a-dea5-43c4-aa02-990d1e38cef8",
    title: "Geopolitical, Settlement",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "a956e28c-2a2b-48e5-88ed-d0a7423ed272",
    title: "Geopolitical, State",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d7a3f5b6-4888-4dd9-bbaa-2f147fd51eff",
    title: "Geopolitical, Stratocracy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "923deb2f-132a-45f1-a5a5-97334de5aab8",
    title: "Geopolitical, Technocracy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4ce561d3-1540-42f1-a51b-8fe17711c1e9",
    title: "Geopolitical, Theocracy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "be28b169-0cfc-4c71-9cd2-c5bb0abb0ba7",
    title: "Geopolitical, Town Council",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9f50cfbf-3b7b-4eb3-966b-25ad661ebc49",
    title: "Geopolitical, Tribe",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0bc28d73-6edb-4106-ba98-313ff69b91b6",
    title: "Geopolitical, Vicekingdom",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2ffccf23-8990-42da-966e-6ca2ff97cb1d",
    title: "Geopolitical, Vicequeendom",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f1bb479f-f27c-4c92-8396-6a79e5de23bb",
    title: "Geopolitical, Village council",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0535338a-4f91-4147-8bc7-670e1f2d2db4",
    title: "Geopolitical, Viscounty",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0fe7cb8b-730c-4071-bfe9-13ef072c0530",
    title: "Government, Law Enforcement",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d5d38000-336e-467f-85b2-2318fb542638",
    title: "Government, Leadership",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "33a60533-c17b-4120-9fbe-5129d5977b29",
    title: "Government, Secret Service",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5c5bc364-a5f7-4bca-9f5c-38583a430186",
    title: "Governmental, Department",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "28d1cb16-ebe7-41bb-ac69-be017907aa21",
    title: "Governmental, Inquisitorial",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2d487d66-67f4-417e-a4c3-ca4730f8dd23",
    title: "Governmental, Ministry",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "45d44842-6dee-4657-a158-a4f0a2fd5f87",
    title: "Governmental, Senate/Parliament",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "156caeae-d0d8-4f99-bfaa-cf58f7c4f547",
    title: "Guild, Adventuring",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "83845957-b511-4abb-9de1-d6289ecd601e",
    title: "Guild, Assassins",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0db4bc12-9465-4d76-9979-67890235a5f4",
    title: "Guild, Craftsmen",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "24bd3599-c536-42e1-bd7a-53ced4720bed",
    title: "Guild, Craftswomen",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "a575092c-e3d9-43a4-a3b8-94b6a06dda22",
    title: "Guild, Fighter / Mercenary",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "64faa251-62d4-44c5-978f-5af70be67a97",
    title: "Guild, Mages",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "308946e0-77fe-44fb-b739-7ab9d338945a",
    title: "Guild, Merchant",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "42a041c0-214f-4ebf-bde0-ab2362678933",
    title: "Guild, Privateers",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "abc2d8f8-6837-4c2e-bbe8-93a214d3e74a",
    title: "Guild, Professional",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "064a2694-ec8f-4049-8897-96a25bac5a71",
    title: "Guild, Thieves",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "6d59dccc-a48a-4b6c-833d-19ea62e5c418",
    title: "Illicit, Cartel",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "10602d33-7679-46a4-a138-be79e04697f9",
    title: "Illicit, Front",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8cfdb918-f17a-4e1d-b016-17520b0dae5d",
    title: "Illicit, Gang",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "64e94fdf-c57d-4f65-9f6f-035de40599a4",
    title: "Illicit, Other",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "bba81eca-00d4-4a67-b2c8-649e30f82d97",
    title: "Illicit, Pirate Crew",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8c2fa579-2b51-4c9d-bf5d-f03e260bd8a8",
    title: "Illicit, Rebel",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ca00d6e1-1fab-4d0f-9410-4d0923b862e4",
    title: "Illicit, Syndicate",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "776d6752-f4c2-4e7f-916d-dc0bf81aab75",
    title: "Illicit, Terrorist group",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "807c7ff2-e4f0-488a-8741-73848d53fe57",
    title: "Information Network",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0a26d7ea-e0a0-48fe-873c-c762ae0e6bc1",
    title: "Megacorporation",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0a1b9e54-de2c-4173-898c-080c2b1a1056",
    title: "Military Order",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "72627d72-8e73-4d83-9f57-fa3b78af7081",
    title: "Military,  Coast Guard",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "cee8195c-5fd2-4c39-a1a7-cca4c0f93a0d",
    title: "Military,  Marine Corps Division",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b67d0441-e27c-40af-83d7-9602af0d1875",
    title: "Military,  Marine Corps Squad",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "beb2318a-6304-44d1-bc39-0216fdaca2ae",
    title: "Military,  Paramilitary/Militia",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "68aaf3a4-bce0-4c69-916d-1c966c161da8",
    title: "Military, Air Force",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "38bc1c62-167f-43f3-a030-b339c4874ba9",
    title: "Military, Air Force Command",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "43688dc7-bda8-4563-9b1f-541bc7c2bda8",
    title: "Military, Air Force Element",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2e68867b-e0a2-4a34-b0a6-c25f8b8183a4",
    title: "Military, Air Force Flight",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "524d0ad0-87bf-43ef-b275-e182cde97f8a",
    title: "Military, Air Force Squadron",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "93d4d912-ca88-4f4a-8776-cc01e6f83a16",
    title: "Military, Air Force Wing",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "48715e99-d130-44f4-af9b-135d8d2fc202",
    title: "Military, Armed Forces",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "92c9ad77-5d2d-409f-92b6-bbe9ba9c5dd8",
    title: "Military, Army",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7b7993d0-be62-4e7e-abe6-2353ef904d04",
    title: "Military, Army Battalion",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4c1c5da1-0a03-489f-a166-e5ddcf4133bb",
    title: "Military, Army Brigade",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b2426736-cadf-48c9-9add-958e63e04103",
    title: "Military, Army Command",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d43caaf0-f381-46b5-98a3-e61956149c34",
    title: "Military, Army Company",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "add7d2ff-c621-4d04-acc2-781958308fa8",
    title: "Military, Army Corps",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "caa1bafb-1e91-4cda-8a52-dc71fb8b06ac",
    title: "Military, Army Division",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4417027a-91ed-4420-b1a2-1de616aa9cc1",
    title: "Military, Army Platoon",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1fb4fdd2-a182-40fa-9018-ba36a2fdf51c",
    title: "Military, Army Regiment",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "373fe820-8997-4e42-973e-414a87d89d1c",
    title: "Military, Army Squad",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "892fb087-667d-4bf9-8cc4-3d446e2b8025",
    title: "Military, Crew",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "292bcec7-7b45-4db4-b38c-c467833e5b16",
    title: "Military, Inquisitorial",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1c607cde-a5d1-46da-b3a4-7ac3786e71eb",
    title: "Military, Intelligence",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f30c8a37-855c-4e03-b635-9e02e5a7c5d4",
    title: "Military, Knightly Order",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "008f8c87-9ac0-41ee-805f-2ce0f4b3d33f",
    title: "Military, Marine Corps",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "54da561a-b667-4d00-ae3e-bddc0aab2f16",
    title: "Military, Marine Corps Company",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "426dc3e3-a718-4091-b5d5-6bf430c418d7",
    title: "Military, Marine Corps Platoon",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2b2aba92-9d5c-42cd-a02a-523961a7db90",
    title: "Military, Marine Corps, Battalion",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0f7294a0-a7b7-4739-b6d2-f0d115ab0ee0",
    title: "Military, Marine Corps, Brigade",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "441b586b-af0e-438b-bcce-a4766457225e",
    title: "Military, Marine Corps, Command",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1aa2b079-03f0-40e2-8c8b-09353f53787b",
    title: "Military, Medical",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f21bb676-40a1-422f-8a7b-1a2a5eca7f6f",
    title: "Military, Mercenary Group",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1f54d688-f029-4aa9-98d6-044df79bdf18",
    title: "Military, Navy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "024c2038-f5a9-4fce-8b20-67647f9d49ec",
    title: "Military, Navy Admiralty",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5f2086f1-6623-46ab-ac4e-586279b5dd1b",
    title: "Military, Navy Fleet",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "5d55c3f4-d454-4c4c-97e2-24bb150e432c",
    title: "Military, Navy Squadron",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1f0c47d9-0dd6-4b5c-913c-a97ad038090e",
    title: "Military, Navy Task force",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "4f2b8bb1-fb44-4cbc-a407-3c16b47d48c1",
    title: "Military, Other",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "322b5eab-013b-46c9-9312-bde63363067f",
    title: "Military, Space navy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "19c2212a-7829-4d97-ba8f-e86bade20c3f",
    title: "Military, Special Operations Force",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1283df88-b793-415f-9c06-b36bb40f232d",
    title: "Political, Activist",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8f5ebd88-6910-431a-9260-46ebdf50d6d6",
    title: "Political, Confederation",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "254a6e2d-db69-440e-af41-6e906650ab36",
    title: "Political, Faction / Party",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e87503be-9f24-4cf5-aae3-9ca4f03659b2",
    title: "Political, Family",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ba532054-dc52-43a9-908c-023a599a482e",
    title: "Political, Federation",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e08ece9f-da53-4df3-8b2a-185c96db8b45",
    title: "Political, independent",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f7114b09-d148-4025-81dd-79b8fc0980fe",
    title: "Political, International",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0d00fa22-d0d6-42eb-8deb-54c84dcf4005",
    title: "Political, Triumvirate",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ddd25abb-f1e0-4af4-ba5a-64d2eeb77831",
    title: "Religious, Archidiaconate",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "77da2cea-166e-428f-b4ec-a9430a23f805",
    title: "Religious, Bishopric",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "6e0123f7-0521-41b1-a9b9-3be6de57979d",
    title: "Religious, Coven",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "dc4c0285-dd63-4c8a-b678-6289d1602def",
    title: "Religious, Cult",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "629ccd57-cef0-43f3-bcae-5603429d3e66",
    title: "Religious, Deanery",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c2317051-8410-4e62-ae82-a21351105d22",
    title: "Religious, Divine Host",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f7ae098a-8dfa-4df0-834d-92d2e181d9fa",
    title: "Religious, Druidic Circle",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e10a6657-730b-460f-8505-578d48a569ee",
    title: "Religious, Financial",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7cbad391-234d-4ec9-b375-f313c17b88b4",
    title: "Religious, Holy Order",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "ce2c2cca-eb10-4fe1-9ee3-9037f985d5e2",
    title: "Religious, Inquisitorial",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1370c563-6dc3-4e6d-b735-467230d31ba3",
    title: "Religious, Monastic Order",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "45d21efb-8331-4e1d-a4c2-9105ce9f30c6",
    title: "Religious, Organised Religion",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "a57952f7-b7e7-41ca-bf23-61bfe8328144",
    title: "Religious, Other",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "79beb5ef-fda5-4f6d-adb4-e593c5ce6696",
    title: "Religious, Pantheon",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "63f513f0-6b58-4033-ac01-9a3b2f1aa440",
    title: "Religious, Parish",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7a860932-ba46-4601-8b85-1f002c639522",
    title: "Religious, Primacy",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "229e26e4-5587-413e-8344-89b6cafb8b70",
    title: "Religious, Sect",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1c1cafe0-e0d2-4bea-acd7-9e57fa2e44c2",
    title: "Religious, Temple",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8b2c967e-95db-4513-9314-02612b79a33e",
    title: "Research, Council",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1b0b3461-c44a-453e-a759-2942f9ca6803",
    title: "Research, Medical",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "907831a7-43e5-4ec4-8699-cfee4cbaf0b5",
    title: "Research, Recurring Symposium",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1e38fbe8-c50c-46c5-93fa-4ad0c03ad2c1",
    title: "Research, Think Tank",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8f95e41d-7480-44a1-bec2-55da08b1d959",
    title: "Secret, Brotherhood",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "306aa561-2d97-4958-869a-c41d61ef25ae",
    title: "Secret, Government",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "a4d2c51e-b809-4331-a1c2-2b70c2aec8fa",
    title: "Secret, Governmental arm",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "14313750-8df1-4e45-97a6-957bdaad93d7",
    title: "Secret, Military",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "11c5eb21-43c4-4104-8552-c7bbbf507d6a",
    title: "Secret, Occult",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0ff7fa2d-3d33-44b8-a542-95529b73a017",
    title: "Secret, Religious sect",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "969383f2-8e44-419f-b313-25c162fa1c1f",
    title: "Secret, Sisterhood",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7d734f1f-f5cc-44bb-88fc-ed335e008432",
    title: "Social, Activist",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "12db151a-dad0-48fc-b7b7-cad9881ea8df",
    title: "Social, Brotherhood",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "3eeced7f-c03f-4cdf-8e5d-57b656859198",
    title: "Social, Clique",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "a3b53c87-a2ba-43f2-887e-211d5476386c",
    title: "Social, Group",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "60611634-010c-4049-8f52-132c553267d7",
    title: "Social, Sisterhood",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0c171279-589b-40f2-bffa-db305967b063",
    title: "Superhero Team",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "OrganizationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
];
