import { SettlementType } from "../settlement";

export const SettlementTypes: SettlementType[] = [
  {
    id: "2d5154ec-be9a-4554-9b38-d17ce037c49c",
    title: "Caravan",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "1e1ecbae-480e-4b52-a814-ebaddfc3f48b",
    title: "Camp, Temporary",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "8167c5e0-6d4c-4a26-a500-30579db49d35",
    title: "Slum",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d753e928-794a-4187-b453-ee53738da0c1",
    title: "Military, Camp",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "fe4c3dff-9c03-4f94-bb03-a31045a19ddb",
    title: "Military, Base",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9581a37f-798a-4e04-9931-63dfba4c56e0",
    title: "Hamlet",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "87cdb8fd-5512-4859-b61c-cdacfeed4a60",
    title: "Outpost / Base",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "0c710938-2ad9-48de-b5b5-605d0bd7cc2a",
    title: "Village",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b78acd16-6817-49f6-b90e-89d2f986d770",
    title: "Neighbourhood",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "e61b1327-f616-49cd-9667-736534c747ed",
    title: "Town",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7db2c3ae-f2c3-4239-97ae-c439d136de47",
    title: "Underground / Vault",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "81de76bb-53b3-4a32-bb52-faf4c1c63b0a",
    title: "Large town",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "35a48295-a78c-4c9d-b3dd-a7cf3b12e62a",
    title: "Quarter",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "f7b18e3f-99dd-4626-9637-6c74f6f09f4f",
    title: "Trade post",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "2506a787-9105-4f84-b955-17a1f4f6d448",
    title: "District",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "383d26c7-2e8c-423e-816f-6064bccf5692",
    title: "Ward",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "9f342bff-25e0-4a42-8551-81b7db4732c6",
    title: "City",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "7eb279f0-c7c4-4747-aea7-c1c5f2441727",
    title: "Large city",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "c464dfd7-d3e6-470c-ac4a-02976d9afb4a",
    title: "Arcology",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "3c05083d-7a5d-423f-9e0d-9f64fefb5030",
    title: "Orbital, Station",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "6f59e813-ee47-4e3a-b6d0-d738d79d5cdc",
    title: "Metropolis",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "808bee6b-9697-4956-a08e-b4fd89819b35",
    title: "Capital",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "76615157-97ac-4dd6-9e62-9c93729dfcef",
    title: "Conurbation",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "67796cc7-7ad4-4767-a0c2-4994beb43ce0",
    title: "Citadel",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "18f7e76e-5f71-4456-9b19-6ff53157ffd4",
    title: "Megalopolis",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "b24336c8-f114-42d2-8597-b9a0ad14deba",
    title: "State",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "d9f12fc7-c864-4afb-9c44-4379d3f5e39c",
    title: "National Territory",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "84926f6a-5d34-43c6-8dac-264527b67f47",
    title: "Ecumenopolis",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  {
    id: "906c8086-92d1-46e1-9d85-c0585d419bd1",
    title: "Starbase",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "LocationType",
    icon: null,
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
];
